-- 스키마 생성
-- CREATE USER 스키마 이름 IDENTIFIED BY 비밀번호
CREATE USER NEWS IDENTIFIED BY 123456;

-- 테이블 생성
CREATE TABLE USERS(
	NAME VARCHAR2(100),
	EMAIL VARCHAR2(150),
	SUB_PATH VARCHAR2(200)
); 

-- 테이블 삭제
DROP TABLE USERS;


-- 출력
SELECT * FROM USERS;

-- 모든 테이블스페이스(tablespace)에 대한 권한을 부여
GRANT UNLIMITED TABLESPACE TO NEWS;